DROP DATABASE LOGIN;
CREATE DATABASE LOGIN;
USE LOGIN;
CREATE TABLE USERS(
ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
LOGIN VARCHAR(255) NOT NULL,
SENHA VARCHAR(35) NOT NULL
);
INSERT INTO USERS(ID,NOME,LOGIN,SENHA) VALUES(NULL,'Rodrigo Elias','ElDigon',md5('delicinha'));